CREATE DATABASE COVID19;
USE COVID19;


CREATE TABLE VACINA (
IDVACINA INT NOT NULL AUTO_INCREMENT
, PAISORIGEM VARCHAR(100)
, ESTAGIOPESQUISA INT
, DT_INICIO DATE
, PRIMARY KEY(IDVACINA)
);

CREATE TABLE APLICACAO_VACINA(
IDAPLICACAO_VACINA INT NOT NULL AUTO_INCREMENT
, AVALIACAO INT
, DATA_APLICACAO DATE
,  PRIMARY KEY (IDAPLICACAO_VACINA),
  CONSTRAINT IDVACINA
    FOREIGN KEY (IDVACINA)
    REFERENCES APLICACAO_VACINA (IDAPLICACAO_VACINA)
    , CONSTRAINT IDPESSOA
    FOREIGN KEY (IDPESSOA)
    REFERENCES APLICACAO_VACINA (IDAPLICACAO_VACINA)
);

CREATE TABLE PESSOA (
IDPESSOA INT NOT NULL AUTO_INCREMENT
, NOME VARCHAR(100)
, DATANASCIMENTO DATE
, SEXO VARCHAR(100)
, CPF VARCHAR(11)
, PRIMARY KEY(IDPESSOA)
);

CREATE TABLE PESQUISADOR (
IDPESQUISADOR INT NOT NULL AUTO_INCREMENT
, INSTITUIÇÃOASSOCIADA VARCHAR(100)
, PRIMARY KEY(IDPESQUISADOR)
, CONSTRAINT IDPESSOA
    FOREIGN KEY (IDPESSOA)
    REFERENCES PESQUISADOR (IDPESQUISADOR)
);

CREATE TABLE PUBLICO (
IDPUBLICO INT NOT NULL AUTO_INCREMENT
, VOLUNTARIO TINYINT
, PRIMARY KEY(IDPUBLICO)
, CONSTRAINT IDPESSOA
FOREIGN KEY(IDPESSOA)
REFERENCES PUBLICO(IDPUBLICO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
);

-- DMLs 
INSERT INTO VACINA (PAISORIGEM, ESTAGIOPESQUISA, DT_INICIO) VALUES ('China', 1,'24/05/2020');

INSERT INTO APLICACAO_VACINA (AVALIACAO, DATA_APLICACAO, IDVACINA, IDPESSOA) VALUES (4, '07/08/2020', 1, 2);

INSERT INTO PESQUISADOR (INSTITUICAOASSOCIADA,IDPESSOA) VALUES ('Shangai University',2);

INSERT INTO PESSOA (NOME, DATANASCIMENTO, SEXO, CPF) VALUES ('Lee Ziang', '12/03/1965','M', '527.576.67-87');

INSERT INTO PUBLICO (VOLUNTARIO, IDPESSOA) VALUES ('Sim',3);